import { useEffect, useRef, useState, type FormEvent } from 'react'
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, ExternalLink, Menu, MousePointer2, Send, X } from 'lucide-react'
import { certifications, experience, projects, services, skills, type Project } from './data'

export const navItems = [['About', 'about'], ['Skills', 'skills'], ['Work', 'work'], ['Experience', 'experience'], ['Certifications', 'certifications'], ['Services', 'services'], ['Contact', 'contact']] as const

export function useReveals() {
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(element => observer.observe(element)); return () => observer.disconnect() }, [])
}

export function Navbar({ menuOpen, setMenuOpen, activeSection }: { menuOpen: boolean; setMenuOpen: (open: boolean) => void; activeSection: string }) {
  const menuButtonRef = useRef<HTMLButtonElement>(null)
  useEffect(() => { if (menuOpen) document.querySelector<HTMLElement>('#mobile-navigation a')?.focus(); const onKey = (event: KeyboardEvent) => event.key === 'Escape' && menuOpen && setMenuOpen(false); document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey) }, [menuOpen, setMenuOpen])
  const menuWasOpen = useRef(false)
  useEffect(() => { if (!menuOpen && menuWasOpen.current) menuButtonRef.current?.focus(); menuWasOpen.current = menuOpen }, [menuOpen])
  const close = () => setMenuOpen(false)
  return <header className="nav-wrap"><nav className="nav container" aria-label="Main navigation"><a className="brand" href="#home" onClick={close}><span className="brand-mark">Z</span><span>ZAIN<span className="muted">.DEV</span></span></a><div id="mobile-navigation" className={`nav-links ${menuOpen ? 'open' : ''}`}>{navItems.map(([label, id]) => <a className={activeSection === id ? 'active' : ''} key={id} href={`#${id}`} aria-current={activeSection === id ? 'location' : undefined} onClick={close}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={close}>Let's talk <ArrowUpRight size={15} /></a></div><button ref={menuButtonRef} className="menu-button" aria-label={menuOpen ? 'Close navigation menu' : 'Open navigation menu'} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></nav></header>
}

export function Hero() { return <section id="home" className="hero section-pad"><div className="hero-grid" aria-hidden="true" /><div className="hero-orbit orbit-one" aria-hidden="true" /><div className="hero-orbit orbit-two" aria-hidden="true" /><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow reveal"><span className="status-dot" /> Available for freelance projects <span className="eyebrow-line" /></div><h1 className="display reveal delay-1">Building digital<br /><em>experiences</em><br />that stand out<span className="lime">.</span></h1><p className="hero-intro reveal delay-2">Full-stack developer and data science student focused on modern websites, applications, and digital experiences with React, Python, AI, and clean design.</p><div className="hero-actions reveal delay-3"><a className="button button-primary" href="#work">View my work <ArrowDownRight size={17} /></a><a className="button button-ghost" href="#contact">Let's connect <ArrowUpRight size={17} /></a></div></div><div className="hero-aside reveal delay-2"><div className="aside-line" /><p>Currently exploring<br /><strong>AI × the web</strong></p><div className="aside-scribble">↘</div></div></div><a className="scroll-cue" href="#about"><MousePointer2 size={14} /> Scroll to explore <span>↓</span></a></section> }

export function SectionKicker({ number, children }: { number: string; children: string }) { return <div className="section-kicker reveal"><span>{number}</span> {children}</div> }
export function About() { return <section id="about" className="about section-pad container"><SectionKicker number="01">A little about me</SectionKicker><div className="about-layout"><div><h2 className="heading reveal">I make the<br /><em>complex</em> feel simple.</h2></div><div className="about-copy reveal delay-1"><p className="lead">I'm Zain, a Full-Stack Developer and Data Science student from Pakistan, passionate about building digital experiences where design and technology come together.</p><p>I build modern websites, web applications, and AI-driven projects with a focus on clean interfaces, smooth user experiences, and solid engineering. I'm constantly exploring new technologies, turning ideas into products, and pushing myself to build better with every project.</p><a className="text-link" href="#contact">Let's build something <ArrowUpRight size={16} /></a></div></div></section> }
export function Skills() { return <section id="skills" className="skills section-pad"><div className="container"><SectionKicker number="02">My toolkit</SectionKicker><div className="section-head"><h2 className="heading reveal">Ideas into<br /><em>interface.</em></h2><p className="section-note reveal delay-1">A flexible stack for bringing a good idea all the way to a great product.</p></div><div className="skill-grid">{skills.map(({ name, icon: Icon, list, note }, i) => <article className={`skill-card reveal delay-${i % 3 + 1}`} key={name}><div className="skill-top"><Icon size={23} strokeWidth={1.5} /><span>0{i + 1}</span></div><h3>{name}</h3><p>{note}</p><div className="skill-list">{list}</div><ChevronRight className="skill-arrow" size={18} /></article>)}</div></div></section> }

function ProjectImage({ project }: { project: Project }) { const [status, setStatus] = useState('loading'); return <div className={`project-image image-${status}`}>{status === 'loading' && <span className="image-status">Loading preview</span>}{status === 'error' && <span className="image-status">Preview unavailable</span>}<img src={project.image} alt={`${project.title} project preview`} loading="lazy" onLoad={() => setStatus('loaded')} onError={() => setStatus('error')} /><div className="project-overlay"><span>View case study</span><ArrowUpRight size={20} /></div></div> }
export function Projects({ onOpen }: { onOpen: (project: Project, trigger: HTMLElement) => void }) { return <section id="work" className="work section-pad container"><SectionKicker number="03">Selected work</SectionKicker><div className="work-heading"><div className="section-head"><h2 className="heading reveal">Selected<br /><em>work.</em></h2><p className="section-note reveal delay-1">Digital experiences, AI products, and automation-focused solutions built for real-world use.</p></div><span className="work-count reveal delay-2">04 projects</span></div><div className="project-grid">{projects.map((project, i) => <article className={`project-card project-${i + 1} ${project.featured ? 'project-featured' : ''} reveal delay-${i % 2 + 1}`} key={project.title} onClick={event => onOpen(project, event.currentTarget)} onKeyDown={event => event.key === 'Enter' && onOpen(project, event.currentTarget)} tabIndex={0}><ProjectImage project={project} /><div className="project-meta"><div className="project-title-block"><div className="project-labels"><span className="project-number">{project.number}</span><span className="project-type">{project.type}</span>{project.featured && <span className="featured-label">Featured project</span>}</div><h3>{project.title}</h3><p className="project-description">{project.description}</p></div><ArrowUpRight className="project-arrow" size={22} /><div className="project-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-actions"><button type="button" onClick={event => { event.stopPropagation(); onOpen(project, event.currentTarget.closest('.project-card') as HTMLElement) }}>View case study <ArrowUpRight size={13} /></button>{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer" onClick={event => event.stopPropagation()}>{project.featured ? 'Live product' : 'Live site'} <ExternalLink size={13} /></a>}</div></div></article>)}</div><div className="work-cta reveal"><div><span>Next up</span><h3>Have a project in mind?</h3><p>Let's build something useful.</p></div><a className="button button-primary" href="#contact">Let's talk <ArrowUpRight size={16} /></a></div></section> }

export function Experience() { return <section id="experience" className="experience section-pad"><div className="container"><SectionKicker number="04">The journey so far</SectionKicker><div className="experience-layout"><h2 className="heading reveal">Still learning.<br /><em>Always building.</em></h2><div className="timeline">{experience.map(([year, title, note], i) => <div className={`timeline-item reveal delay-${i + 1}`} key={title}><span className="timeline-year">{year}</span><div><h3>{title}</h3><p>{note}</p></div><ArrowUpRight size={18} /></div>)}</div></div></div></section> }
export function Certifications() { return <section id="certifications" className="certifications section-pad container"><SectionKicker number="05">Certifications & training</SectionKicker><div className="section-head"><h2 className="heading reveal">Proof of<br /><em>progress.</em></h2><p className="section-note reveal delay-1">Verified learning across AI, analytics, and cloud technology.</p></div><div className="certificate-grid">{certifications.map((certificate, i) => <article className={`certificate-card reveal delay-${i % 3 + 1}`} key={certificate.name}><div className="certificate-top"><span className="certificate-number">0{i + 1}</span><span className="certificate-issuer">{certificate.issuer}</span></div><h3>{certificate.name}</h3><p>{certificate.description}</p><div className="certificate-skills">{certificate.skills.map(skill => <span key={skill}>{skill}</span>)}</div>{certificate.date && <span className="certificate-date">Completed · {certificate.date}</span>}{certificate.credentialUrl && <a className="certificate-link" href={certificate.credentialUrl} target="_blank" rel="noreferrer">View credential <ExternalLink size={13} /></a>}</article>)}</div></section> }
export function Services() { return <section id="services" className="services section-pad container"><SectionKicker number="06">What I can build</SectionKicker><div className="section-head"><h2 className="heading reveal">Useful things,<br /><em>beautifully made.</em></h2></div><div className="service-list">{services.map(([service, note], i) => <div className="service-row reveal" key={service}><span>0{i + 1}</span><div><h3>{service}</h3><p>{note}</p></div><ArrowUpRight size={21} /></div>)}</div></section> }

const CONTACT_ENDPOINT = import.meta.env.VITE_CONTACT_ENDPOINT || ''
export function Contact() { const [state, setState] = useState<'idle' | 'sending' | 'success' | 'error'>('idle'); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (state === 'sending') return; if (!CONTACT_ENDPOINT) { setError('Add your real form endpoint in .env before sending messages.'); setState('error'); return } setState('sending'); try { const response = await fetch(CONTACT_ENDPOINT, { method: 'POST', headers: { Accept: 'application/json' }, body: new FormData(event.currentTarget) }); if (!response.ok) throw new Error('Request failed'); setState('success'); event.currentTarget.reset() } catch { setError('Something went wrong while sending. Please email hello@zain.dev instead.'); setState('error') } } return <section id="contact" className="contact section-pad"><div className="contact-glow" aria-hidden="true" /><div className="container contact-inner"><SectionKicker number="07">Start a conversation</SectionKicker><h2 className="display contact-title reveal">Have a project<br />in <em>mind?</em><span className="lime"> Let's talk.</span></h2><div className="contact-grid"><div className="contact-pitch reveal delay-1"><p>Good work starts with a good conversation. Tell me a little about what you're making, and I'll get back to you soon.</p><a href="mailto:hello@zain.dev" className="email-link">hello@zain.dev <ArrowUpRight size={17} /></a><div className="socials"><a aria-label="GitHub profile placeholder" href="#contact">GH</a><a aria-label="LinkedIn profile placeholder" href="#contact">in</a><a aria-label="Instagram profile placeholder" href="#contact">ig</a></div><small className="placeholder-note">Social profile URLs need to be added.</small></div><form className="contact-form reveal delay-2" onSubmit={submit} aria-busy={state === 'sending'}>{state === 'success' ? <div className="form-success" role="status"><Check size={26} /><h3>Message sent.</h3><p>Thanks for reaching out. I'll be in touch shortly.</p><button type="button" onClick={() => setState('idle')}>Send another</button></div> : <>{state === 'error' && <p className="form-error" role="alert">{error}</p>}<label>Name<input required autoComplete="name" name="name" placeholder="Your name" /></label><label>Email<input required autoComplete="email" type="email" name="email" placeholder="you@company.com" /></label><label>Subject<input required name="subject" placeholder="How can I help?" /></label><label>Tell me about it<textarea required name="message" placeholder="A few words about your project..." rows={4} /></label><button className="button button-primary" type="submit" disabled={state === 'sending'}>{state === 'sending' ? 'Sending...' : 'Send message'} <Send size={16} /></button></>}</form></div></div></section> }

export function Footer() { return <footer className="footer"><div className="container footer-inner"><a className="brand" href="#home"><span className="brand-mark">Z</span><span>ZAIN<span className="muted">.DEV</span></span></a><div className="footer-links">{navItems.map(([label, id]) => <a key={id} href={`#${id}`}>{label}</a>)}</div><p>Building modern digital experiences<br />with code, creativity, and technology.</p><span className="footer-note">© 2026 Zain</span></div></footer> }

export function ProjectModal({ project, trigger, onClose }: { project: Project; trigger: HTMLElement | null; onClose: () => void }) { const closeRef = useRef<HTMLButtonElement>(null); useEffect(() => { closeRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'Tab') { const focusable = Array.from(document.querySelectorAll<HTMLElement>('.project-modal a, .project-modal button')); const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } } }; document.addEventListener('keydown', onKey); return () => { document.removeEventListener('keydown', onKey); requestAnimationFrame(() => trigger?.focus()) } }, [onClose, trigger]); return <div className="modal-backdrop" role="presentation" onClick={onClose}><div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title" onClick={event => event.stopPropagation()}><button ref={closeRef} className="modal-close" aria-label="Close case study" onClick={onClose}><X size={19} /></button><img src={project.image} alt={`${project.title} preview`} /><div className="modal-content"><span className="project-type">{project.number} / {project.type}</span><h2 id="project-modal-title">{project.title}</h2><div className="case-study-section"><span>Project overview</span><p>{project.description}</p></div><div className="case-study-section"><span>Purpose</span><p>{project.details}</p></div><div className="case-study-section"><span>Tech stack</span><div className="project-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="case-study-meta"><span>Project type <strong>{project.projectType}</strong></span></div><div className="modal-actions">{project.liveUrl && <a className="button button-primary" href={project.liveUrl} target="_blank" rel="noreferrer">{project.featured ? 'View live product' : 'View live site'} <ExternalLink size={16} /></a>}{project.githubUrl && <a className="button button-ghost" href={project.githubUrl} target="_blank" rel="noreferrer">View project <ExternalLink size={16} /></a>}</div></div></div></div> }